{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import tdmclient.notebook\n",
    "import tdmclient.tools\n",
    "import numpy as np"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Connecting to the Thymio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 168,
   "metadata": {},
   "outputs": [],
   "source": [
    "await tdmclient.notebook.start()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## The different step options communicated to the Thymio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 169,
   "metadata": {},
   "outputs": [],
   "source": [
    "def turn90(direction, speed):\n",
    "    set_var(motor_right_target=(direction * (-1)) * speed ,motor_left_target=(direction * 1) * speed)\n",
    "    time.sleep(1.15)\n",
    "    set_var(motor_right_target=0,motor_left_target=0)\n",
    "\n",
    "def forward (speed):\n",
    "    set_var(motor_right_target=speed,motor_left_target=speed)\n",
    "    time.sleep(2.9)\n",
    "    set_var(motor_right_target=0,motor_left_target=0)\n",
    "\n",
    "def moveNorth(previousStep):\n",
    "    dist = 200\n",
    "    turnspeed = 200\n",
    "    if previousStep == 1:\n",
    "        turn90(-1, turnspeed)\n",
    "    elif previousStep == 2:\n",
    "        turn90(1, turnspeed)\n",
    "        turn90(1, turnspeed)\n",
    "    elif previousStep == 3:\n",
    "        turn90(1, turnspeed)\n",
    "    forward(dist)\n",
    "\n",
    "def moveEast(previousStep):\n",
    "    dist = 190\n",
    "    turnspeed = 190\n",
    "    if previousStep == 0:\n",
    "        turn90(1, turnspeed)\n",
    "    elif previousStep == 2:\n",
    "        turn90(-1, turnspeed)\n",
    "    elif previousStep == 3:\n",
    "        turn90(1, turnspeed)\n",
    "        turn90(1, turnspeed)\n",
    "    forward(dist)\n",
    "\n",
    "def moveSouth(previousStep):\n",
    "    dist = 200\n",
    "    turnspeed = 200\n",
    "    if previousStep == 0:\n",
    "        turn90(1, turnspeed)\n",
    "        turn90(1, turnspeed)\n",
    "    elif previousStep == 1:\n",
    "        turn90(1, turnspeed)\n",
    "    elif previousStep == 3:\n",
    "        turn90(-1, turnspeed)\n",
    "    forward(dist)\n",
    "\n",
    "def moveWest(previousStep):\n",
    "    dist = 200\n",
    "    turnspeed = 200\n",
    "    if previousStep == 0:\n",
    "        turn90(-1, turnspeed)\n",
    "    elif previousStep == 1:\n",
    "        turn90(1, turnspeed)\n",
    "        turn90(1, turnspeed)\n",
    "    elif previousStep == 2:\n",
    "        turn90(1, turnspeed)\n",
    "    forward(dist)\n",
    "\n",
    "def executeStep(step, previousStep):\n",
    "    print(step)\n",
    "    if step == 0:\n",
    "        print(\"moving North\")\n",
    "        moveNorth(previousStep)\n",
    "    elif step == 1:\n",
    "        print(\"moving East\")\n",
    "        moveEast(previousStep)\n",
    "    elif step == 2:\n",
    "        print(\"moving Sourth\")\n",
    "        moveSouth(previousStep)\n",
    "    elif step == 3:\n",
    "        print(\"moving West\")\n",
    "        moveWest(previousStep)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Importing the training result and executing the different Steps"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 173,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[0 0 3 2 3 0 3 3 2 1 2 2 3 0]\n",
      "0\n",
      "0\n",
      "3\n",
      "2\n",
      "3\n",
      "0\n",
      "3\n",
      "3\n",
      "2\n",
      "1\n",
      "2\n",
      "2\n",
      "3\n",
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-3:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-12:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-7:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-19:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-11:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-10:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-18:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-6:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-14:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-15:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-8:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-13:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-20:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-4:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-16:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-9:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-5:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "Exception in thread Thread-17:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\threading.py\", line 980, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "        raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    self.run()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 73, in run\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "        return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    packet = self.read_packet()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 66, in read_packet\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "        packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "        packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    raise error\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 59, in read_packet\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "        return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "        packet_len = self.read_uint32()\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 46, in read_uint32\n",
      "return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "    b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "        return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n",
      "b = self.io.read(4)\n",
      "  File \"c:\\Users\\Anna\\anaconda3\\envs\\vsc-jupyter-kernel\\lib\\site-packages\\tdmclient\\tcp.py\", line 99, in read\n",
      "    return self.socket.recv(n)\n",
      "ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen\n"
     ]
    }
   ],
   "source": [
    "StepsArray = np.loadtxt('StepArray.txt', dtype=int)\n",
    "print(StepsArray)\n",
    "previousStep=3\n",
    "\n",
    "for i in range(StepsArray.size):\n",
    "    executeStep(StepsArray[i], previousStep)\n",
    "    previousStep=StepsArray[i]\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<coroutine object stop at 0x0000022A029577C0>"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tdmclient.notebook.stop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
